### ISSUE TITLE
XrmMock.OptionSetValueMock is not a constructor

### ISSUE THREAD

**Issue by vleong2332** [camelCaseDave/xrm-mock-generator#1]
I got an error when trying to create option set attribute in my test.

```
Message:
    TypeError: XrmMock.OptionSetValueMock is not a constructor
  Stack:
    TypeError: XrmMock.OptionSetValueMock is not a constructor
        at Attribute.createOptionSet (/Users/Vicky/projects/PORT/WebResources/node_modules/xrm-mock-generator/dist/xrm-mock-generator.js:1773:39)
        at UserContext.<anonymous> (/Users/Vicky/projects/PORT/WebResources/src/Scripts/project_form_spec.js:30:54)
```
Any idea why?

Node 8.4.0
npm 5.4.2
OS macOS Sierra 10.12.6

**Comment by camelCaseDave** [comment]
Resolved by PR in associated project xrm-mock
